// <auto-generated />
namespace Oct10_2017GamesMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTeamsReal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTeamsReal));
        
        string IMigrationMetadata.Id
        {
            get { return "201710102251155_addTeamsReal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
